CycleStore.Web.MVC/Controllers/GlobalAboutController.cs
using Buisness.Abstract;
using CycleStore.Web.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CycleStore.Web.MVC.Controllers
{
    public class GlobalAboutController : Controller
    {
        private readonly IAboutService _aboutService;
        private readonly IActivityService _activityService;
        private readonly IBestRacerService _bestRacerService;
        private readonly ICycleService _cycleService;
        private readonly IServiceService _serviceService;
        private readonly ITestimonialService _testimonialService;

        public GlobalAboutController(IAboutService aboutService, IActivityService activityService, IBestRacerService bestRacerService, ICycleService cycleService, IServiceService serviceService, ITestimonialService testimonialService)
        {
            _aboutService = aboutService;
            _activityService = activityService;
            _bestRacerService = bestRacerService;
            _serviceService = serviceService;
            _testimonialService = testimonialService;
            _cycleService = cycleService;
        }
        public IActionResult Index()
        {
            var aboutData = _aboutService.GetAll().Data;
            var activityData = _activityService.GetAll().Data;
            var bestRacerData = _bestRacerService.GetAll().Data;
            var serviceData = _serviceService.GetAll().Data;
            AboutViewModel viewModel = new()
            {
                Abouts = aboutData,
                Activities = activityData,
                BestRacers = bestRacerData,
                Services = serviceData,
            };
            return View(viewModel);
        }
    }
}

CycleStore.Web.MVC/Controllers/GlobalCartController.cs
using Buisness.Abstract;
using DataAccess.Abstract;
using Entities.Concrete.MemberShip;
using Entities.Concrete.TableModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CycleStore.Web.MVC.Controllers
{
    [Authorize]

    public class GlobalCartController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICartService _cartService;
        private readonly ICartItemService _cartItemService;

        public GlobalCartController(UserManager<ApplicationUser> userManager, ICartService cartService, ICartItemService cartItemService)
        {
            _userManager = userManager;
            _cartService = cartService;
            _cartItemService = cartItemService;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["User"] = await _userManager.GetUserAsync(User);
            var data = _cartItemService.GetAll().Data;
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> AddBikeToCart(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var cart = _cartService.GetAll().Data.Find(x => x.UserId == user?.Id);
            if (cart == null)
            {
                Cart newCart = new()
                {
                    UserId = user.Id
                };
                
                _cartService.Add(newCart);
                cart = newCart; 
            }

            CartItem newCartItem = new CartItem()
            {
                CartId = cart.Id,
                CycleId = id,
                Quantity = 1
            };
            var existingCartItem = _cartItemService.GetAll().Data.Find(x => x.CartId == newCartItem.CartId && x.CycleId == newCartItem.CycleId);

            if (existingCartItem == null)
            {
                var result = _cartItemService.Add(newCartItem);
                if (!result.IsSuccess) return Json(new { isSuccess = false });
                return Json(new { isSuccess = true });
            }
            else
            {
                existingCartItem.Quantity++;
                var result = _cartItemService.Update(existingCartItem);
                if (!result.IsSuccess) return Json(new { isSuccess = false });
                return Json(new { isSuccess = true });
            }
        }

        [HttpPost]
        public async Task<IActionResult> PlusBike(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var existingCartItem = _cartItemService.GetAll().Data.Find(x =>x.UserId == user.Id && x.CycleId == id);
            if (existingCartItem != null)
            {
                existingCartItem.Quantity++;
                var result = _cartItemService.Update(existingCartItem);
                if (!result.IsSuccess) return Json(new { isSuccess = false });
                return Json(new { isSuccess = true });
            }

            return Json(new { isSuccess = false });
        }

        [HttpPost]
        public async Task<IActionResult> MinusBike(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var existingCartItem = _cartItemService.GetAll().Data.Find(x => x.UserId == user.Id && x.CycleId == id);
            if (existingCartItem != null && existingCartItem.Quantity > 1)
            {
                existingCartItem.Quantity--;
                var result = _cartItemService.Update(existingCartItem);
                if (!result.IsSuccess) return Json(new { isSuccess = false });
                return Json(new { isSuccess = true });
            }

            return Json(new { isSuccess = false });
        }

        [HttpPost]
        public IActionResult RemoveBike(int id)
        {
            var result = _cartItemService.Delete(id);
            if (!result.IsSuccess) return Json(new { isSuccess = false });
            return Json(new { isSuccess = true });
        }
    }
}

CycleStore.Web.MVC/Controllers/GlobalContactController.cs
using Buisness.Abstract;
using Entities.Concrete.Dtos;
using Entities.Concrete.MemberShip;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CycleStore.Web.MVC.Controllers
{
    public class GlobalContactController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IContactService _contactService;

        public GlobalContactController(UserManager<ApplicationUser> userManager, IContactService contactService)
        {
            _userManager = userManager;
            _contactService = contactService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["User"] = await _userManager.GetUserAsync(User);
            return View();
        }

        [HttpPost]
        public IActionResult Create(ContactCreateDto dto)
        {
            var result = _contactService.Add(dto);
            if (!result.IsSuccess)
            {
                return Json(new { isSuccess = false });
            }
            return Json(new { isSuccess = true });
        }
    }
}

CycleStore.Web.MVC/Controllers/ShopController.cs
using Buisness.Abstract;
using CycleStore.Web.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;


namespace CycleStore.Web.MVC.Controllers
{
    public class ShopController : Controller
    {

        private readonly IBestRacerService _bestRacerService;
        private readonly ICycleService _cycleService;
        private readonly IBigSaleService _bigSaleService;

        public ShopController(IBestRacerService bestRacerService, ICycleService cycleService, IBigSaleService bigSaleService)
        {
            _bestRacerService = bestRacerService;
            _cycleService = cycleService;
            _bigSaleService = bigSaleService;
        }

        public IActionResult Index()
        {
            var bestRacerData = _bestRacerService.GetAll().Data;
            var cycleData = _cycleService.GetProductWithCycleCategoryId().Data;
            var bigSaleData = _bigSaleService.GetAll().Data;

            ShopViewModel viewModel = new()
            {
                BestRacers = bestRacerData,
                Cycles = cycleData,
                BigSales = bigSaleData
            };
            return View(viewModel);
        }
    }
}

CycleStore.Web.MVC/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">

<!-- Mirrored from kamleshyadav.com/html/cycling/version-3/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 07 May 2024 14:53:47 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cycling - Responsive HTML Template</title>
    <link rel="icon" type="image/icon" href="assets/images/fav.png">
   
    <link href="~/assets/css/all.min.css" rel="stylesheet" />
    <link href="~/assets/css/animate.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/font.css" rel="stylesheet" />
    <link href="~/assets/css/magnific-popup.min.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/swiper.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <!--Loader Start-->
    <div class="loader_wrapper">
        <div class='loader'>
            <img src="~/assets/images/loader.gif" alt="loader">
        </div>
    </div>
    <div class="cl-main-wraper">
       
       @*  <partial name="_Navbar"/> *@
       @await Html.PartialAsync("_Navbar")
        @RenderBody()
     
        <!-- footer start -->
        <div class="cl-footer spacer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="cl-footer-logo cl-footer-widget">
                            <img src="~/assets/images/logo.png" alt="image">
                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</p>
                            <ul class="cl-social-icons">
                                <li>
                                    <a href="https://www.facebook.com/ibrahimLicav1d?mibextid=ZbWKwL"><i class="fab fa-facebook-f"></i></a>
                                </li>
                               
                                <li>
                                    <a href="https://www.instagram.com/_ibrahimli._._._"><i class="fab fa-google-plus-g"></i></a>
                                </li>
                                <li>
                                    <a href="javascript:;"><i class="fab fa-linkedin-in"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="cl-footer-widget">
                            <h2 class="cl-foot-title">Categories</h2>
                            <div class="cl-footer-links">
                                <ul>
                                    <li>
                                        <a href="javascript:;">Road bikes</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Mountain bikes</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Hybrid bikes</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Cyclocross bikes</a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">Folding bikes</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="cl-footer-widget">
                            <h2 class="cl-foot-title">Overviews</h2>
                            <div class="cl-footer-links">
                                <ul>
                                    <li>
                                        <a href="index.html">Home</a>
                                    </li>
                                    <li>
                                        <a href="about.html">About Us</a>
                                    </li>
                                    <li>
                                        <a href="cart.html">Cart</a>
                                    </li>
                                    <li>
                                        <a href="checkout.html">Checkout</a>
                                    </li>
                                    <li>
                                        <a href="contact.html">Contact Us</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="cl-footer-widget">
                            <h2 class="cl-foot-title">Newsletter</h2>
                            <div class="cl-footer-newsletter">
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</p>
                                <form>
                                    <input type="email" placeholder="Email here...">
                                    <button class="cl-btn">Subscribe</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer end -->
        <!-- copyright start -->
        <div class="cl-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="cl-copytext">
                            <p>Copyright &copy; 2024, Cycling. All Rights Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- copyright end -->
       
       
    </div>
    <script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="~/assets/js/jquery.js"></script>
    <script src="~/assets/js/swiper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/wow.js"></script>
    <script src="~/assets/js/SmoothScroll.min.js"></script>
    <script src="~/assets/js/magnific-popup.min.js"></script>
    <script src="~/assets/js/custom.js"></script>
    <script>(function () { if (!document.body) return; var js = "window['__CF$cv$params']={r:'88020a9718e39dc6',t:'MTcxNTA5MzYyNi4xNTUwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='../../../cdn-cgi/challenge-platform/h/b/scripts/jsd/ce7818f50e39/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);"; var _0xh = document.createElement('iframe'); _0xh.height = 1; _0xh.width = 1; _0xh.style.position = 'absolute'; _0xh.style.top = 0; _0xh.style.left = 0; _0xh.style.border = 'none'; _0xh.style.visibility = 'hidden'; document.body.appendChild(_0xh); function handler() { var _0xi = _0xh.contentDocument || _0xh.contentWindow.document; if (_0xi) { var _0xj = _0xi.createElement('script'); _0xj.innerHTML = js; _0xi.getElementsByTagName('head')[0].appendChild(_0xj); } } if (document.readyState !== 'loading') { handler(); } else if (window.addEventListener) { document.addEventListener('DOMContentLoaded', handler); } else { var prev = document.onreadystatechange || function () { }; document.onreadystatechange = function (e) { prev(e); if (document.readyState !== 'loading') { document.onreadystatechange = prev; handler(); } }; } })();</script>
    @RenderSection("Scripts", false)
    
</body>

<!-- Mirrored from kamleshyadav.com/html/cycling/version-3/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 07 May 2024 14:54:00 GMT -->
</html>

CycleStore.Web.MVC/Views/Shared/_Navbar.cshtml
<!-- Navbar start -->
<div class="cl-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="cl-logo">
                    <a href="/"><img src="/assets/images/logo.png" alt="image"></a>
                </div>
            </div>
            <div class="col-md-8">
                <div class="cl-main-menu">
                    <div class="cl-navbar">
                        <ul>
                            <li><a href="/">Home</a></li>
                            @*  <li class="cl-has-submenu">
                            <a href="javascript:;">Store</a>
                            <ul class="cl-mega-menu">
                            <li>
                            <ul>
                            <li>
                            <a href="javascript:;">Road bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Mountain bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Hybrid bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Cyclocross bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Folding bikes</a>
                            </li>
                            </ul>
                            </li>
                            <li>
                            <ul>
                            <li>
                            <a href="javascript:;">Bicycle Pedal</a>
                            </li>
                            <li>
                            <a href="javascript:;">Gear Chain</a>
                            </li>
                            <li>
                            <a href="javascript:;">Hand Grip</a>
                            </li>
                            <li>
                            <a href="javascript:;">Seat Cover</a>
                            </li>
                            <li>
                            <a href="javascript:;">Front Disk</a>
                            </li>
                            </ul>
                            </li>
                            <li>
                            <ul>
                            <li>
                            <a href="javascript:;">Road bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Mountain bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Hybrid bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Cyclocross bikes</a>
                            </li>
                            <li>
                            <a href="javascript:;">Folding bikes</a>
                            </li>
                            </ul>
                            </li>
                            <li>
                            <ul>
                            <li>
                            <a href="javascript:;">Bicycle Pedal</a>
                            </li>
                            <li>
                            <a href="javascript:;">Gear Chain</a>
                            </li>
                            <li>
                            <a href="javascript:;">Hand Grip</a>
                            </li>
                            <li>
                            <a href="javascript:;">Seat Cover</a>
                            </li>
                            <li>
                            <a href="javascript:;">Front Disk</a>
                            </li>
                            </ul>
                            </li>
                            </ul>
                            </li*@
                            <li><a asp-controller="GlobalAbout" asp-action="Index">About</a></li>
                            <li><a asp-controller="Shop" asp-action="Index">Shop</a></li>
                            <li><a asp-controller="GlobalShippingAdress" asp-action="Create">Shipping Adress</a></li>




                            @* <li class="cl-has-submenu">
                            <a href="javascript:;">Shop</a>
                            <ul class="cl-sub-menu">
                            <li><a href="shop.html">Shop</a></li>
                            <li><a href="product-detail.html">Product Detail</a></li>

                            </ul> *@
                            </li>
                            <li><a asp-controller="GlobalContact" asp-action="Create">Contact Us</a></li>
                        </ul>
                    </div>
                    <div class="cl-menu-toggle">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    <div class="cl-head-icons">
                        <ul>
                            <li>
                                <a asp-action="Index" asp-controller="GlobalCart">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 21">
                                        <path d="M1619.26,77.86a2.069,2.069,0,1,0,2.11,2.069A2.095,2.095,0,0,0,1619.26,77.86Zm0.63,2.069a0.628,0.628,0,0,1-.63.616,0.616,0.616,0,1,1,0-1.231A0.629,0.629,0,0,1,1619.89,79.929Zm6.03-2.069a2.069,2.069,0,1,0,2.1,2.069A2.088,2.088,0,0,0,1625.92,77.86Zm0.62,2.069a0.625,0.625,0,1,1-.62-0.616A0.619,0.619,0,0,1,1626.54,79.929Zm5.17-15.106a1.267,1.267,0,0,0-.98-0.46H1614.4l-0.3-1.422a1.244,1.244,0,0,0-.74-0.892l-2.32-.991a0.759,0.759,0,0,0-.57-0.009,0.721,0.721,0,0,0-.42.943,0.7,0.7,0,0,0,.4.4l2.22,0.948,2.54,12.106a1.275,1.275,0,0,0,1.25.995h12.69a0.727,0.727,0,1,0,0-1.453h-12.52l-0.23-1.072h12.85a1.264,1.264,0,0,0,1.24-1l1.48-7.059A1.191,1.191,0,0,0,1631.71,64.823Zm-1.24.994-1.39,6.646H1616.1l-1.4-6.646h15.77Z" transform="translate(-1610 -61)" />
                                    </svg>
                                </a>
                            </li>

                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <li>
                                        <a asp-action="Index" asp-controller="Home" asp-area="Dashboard" class="">
                                            <svg with="18px" height="18px" fill="#000000" viewBox="0 0 1920 1920" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M276.941 440.584v565.722c0 422.4 374.174 625.468 674.71 788.668l8.02 4.292 8.131-4.292c300.537-163.2 674.71-366.268 674.71-788.668V440.584l-682.84-321.657L276.94 440.584Zm682.73 1479.529c-9.262 0-18.523-2.372-26.993-6.89l-34.9-18.974C588.095 1726.08 164 1495.906 164 1006.306V404.78c0-21.91 12.65-41.788 32.414-51.162L935.727 5.42c15.134-7.228 32.866-7.228 48 0l739.313 348.2c19.765 9.374 32.414 29.252 32.414 51.162v601.525c0 489.6-424.207 719.774-733.779 887.943l-34.899 18.975c-8.47 4.517-17.731 6.889-27.105 6.889Zm467.158-547.652h-313.412l-91.595-91.482v-83.803H905.041v-116.78h-83.69l-58.503-58.504c-1.92.113-3.84.113-5.76.113-176.075 0-319.285-143.21-319.285-319.285 0-176.075 143.21-319.398 319.285-319.398 176.075 0 319.285 143.323 319.285 319.398 0 1.92 0 3.84-.113 5.647l350.57 350.682v313.412Zm-266.654-112.941h153.713v-153.713L958.462 750.155l3.953-37.27c1.017-123.897-91.595-216.621-205.327-216.621S550.744 588.988 550.744 702.72c0 113.845 92.612 206.344 206.344 206.344l47.21-5.309 63.811 63.7h149.873v116.78h116.781v149.986l25.412 25.299Zm-313.4-553.57c0 46.758-37.949 84.706-84.706 84.706-46.758 0-84.706-37.948-84.706-84.706s37.948-84.706 84.706-84.706c46.757 0 84.706 37.948 84.706 84.706" fill-rule="evenodd"></path> </g></svg>
                                        </a>
                                    </li>


                                }
                                <li>
                                    <a asp-action="LogOut" asp-controller="Account">
                                        <svg width="18px" height="18px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                            <g id="SVGRepo_iconCarrier">
                                                <path d="M12.9999 2C10.2385 2 7.99991 4.23858 7.99991 7C7.99991 7.55228 8.44762 8 8.99991 8C9.55219 8 9.99991 7.55228 9.99991 7C9.99991 5.34315 11.3431 4 12.9999 4H16.9999C18.6568 4 19.9999 5.34315 19.9999 7V17C19.9999 18.6569 18.6568 20 16.9999 20H12.9999C11.3431 20 9.99991 18.6569 9.99991 17C9.99991 16.4477 9.55219 16 8.99991 16C8.44762 16 7.99991 16.4477 7.99991 17C7.99991 19.7614 10.2385 22 12.9999 22H16.9999C19.7613 22 21.9999 19.7614 21.9999 17V7C21.9999 4.23858 19.7613 2 16.9999 2H12.9999Z" fill="#000000"></path> <path d="M13.9999 11C14.5522 11 14.9999 11.4477 14.9999 12C14.9999 12.5523 14.5522 13 13.9999 13V11Z" fill="#000000"></path> <path d="M5.71783 11C5.80685 10.8902 5.89214 10.7837 5.97282 10.682C6.21831 10.3723 6.42615 10.1004 6.57291 9.90549C6.64636 9.80795 6.70468 9.72946 6.74495 9.67492L6.79152 9.61162L6.804 9.59454L6.80842 9.58848C6.80846 9.58842 6.80892 9.58778 5.99991 9L6.80842 9.58848C7.13304 9.14167 7.0345 8.51561 6.58769 8.19098C6.14091 7.86637 5.51558 7.9654 5.19094 8.41215L5.18812 8.41602L5.17788 8.43002L5.13612 8.48679C5.09918 8.53682 5.04456 8.61033 4.97516 8.7025C4.83623 8.88702 4.63874 9.14542 4.40567 9.43937C3.93443 10.0337 3.33759 10.7481 2.7928 11.2929L2.08569 12L2.7928 12.7071C3.33759 13.2519 3.93443 13.9663 4.40567 14.5606C4.63874 14.8546 4.83623 15.113 4.97516 15.2975C5.04456 15.3897 5.09918 15.4632 5.13612 15.5132L5.17788 15.57L5.18812 15.584L5.19045 15.5872C5.51509 16.0339 6.14091 16.1336 6.58769 15.809C7.0345 15.4844 7.13355 14.859 6.80892 14.4122L5.99991 15C6.80892 14.4122 6.80897 14.4123 6.80892 14.4122L6.804 14.4055L6.79152 14.3884L6.74495 14.3251C6.70468 14.2705 6.64636 14.1921 6.57291 14.0945C6.42615 13.8996 6.21831 13.6277 5.97282 13.318C5.89214 13.2163 5.80685 13.1098 5.71783 13H13.9999V11H5.71783Z" fill="#000000"></path>
                                            </g>
                                        </svg>
                                    </a>
                                </li>

                            }
                            else
                            {
                                <li>
                                    <a asp-action="Login" asp-controller="Account">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                            <path fill-rule="evenodd" class="shp0" d="M19.46 19.13C19.01 19.68 18.34 20 17.63 20L14.1 20C13.67 20 13.32 19.65 13.32 19.22C13.32 18.79 13.67 18.44 14.1 18.44L17.63 18.44C17.96 18.44 18.16 18.25 18.25 18.14C18.41 17.95 18.47 17.7 18.42 17.46C18.33 17.03 18.6 16.62 19.02 16.53C19.45 16.44 19.86 16.71 19.95 17.14C20.09 17.84 19.92 18.57 19.46 19.13ZM9.13 10.66C5.45 11.04 2.35 13.78 1.58 17.46C1.53 17.7 1.59 17.95 1.75 18.14C1.84 18.25 2.04 18.44 2.37 18.44L5.78 18.44C6.21 18.44 6.56 18.79 6.56 19.22C6.56 19.65 6.21 20 5.78 20L2.37 20C1.66 20 0.99 19.68 0.54 19.13C0.08 18.57 -0.1 17.84 0.05 17.14C0.52 14.88 1.76 12.84 3.55 11.37C4.52 10.56 5.64 9.96 6.82 9.57C5.53 8.6 4.69 7.05 4.69 5.31C4.69 2.38 7.07 0 10 0C12.93 0 15.31 2.38 15.31 5.31C15.31 7.05 14.47 8.6 13.18 9.56C15.3 10.26 17.16 11.65 18.45 13.57C18.69 13.92 18.59 14.41 18.23 14.65C17.87 14.89 17.39 14.79 17.15 14.44C15.69 12.27 13.36 10.89 10.79 10.65C9.89 10.52 9.13 10.66 9.13 10.66ZM9.82 9.06C9.88 9.06 9.94 9.06 10 9.06C10.06 9.06 10.12 9.06 10.19 9.06C12.17 8.96 13.75 7.32 13.75 5.31C13.75 3.25 12.07 1.56 10 1.56C7.93 1.56 6.25 3.25 6.25 5.31C6.25 7.32 7.83 8.96 9.82 9.06Z" />
                                        </svg>
                                    </a>
                                </li>

                            }

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Navbar end -->